services:
  web:
    build: .  # 현재 디렉토리에서 Dockerfile을 빌드
    ports:
      - "30309:30309"  # 30309 포트를 외부로 매핑
    depends_on:
      - db  # db 서비스가 먼저 실행되도록 설정
    environment:
      - FLASK_ENV=development

  db:
    image: mysql:8.0  # MySQL 8.0 버전 이미지 사용
    environment:
      MYSQL_ROOT_PASSWORD: password  # 루트 비밀번호 설정
      MYSQL_DATABASE: test_db  # 초기 데이터베이스 이름 설정
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # init.sql 파일을 MySQL 초기화 디렉토리로 복사
    ports:
      - "3306:3306"  # MySQL 포트 외부로 노출
